config/routes.rb
Rails.application.routes.draw do
  resources :csv_parsers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'csv_parsers#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/csv_parsers_controller.rb
class CsvParsersController < ApplicationController
  require 'csv'
  def index
    @new_data = []
  end

  def new
  end

  def create
    # csv_text = File.read('...')
    @new_data = []

    csv_file = params[:csv_file]  #get the csv file from form
    CSV.foreach(csv_file.path, {:quote_char =>"\'", :headers => true}) do |row|
      process_csv(row)   #process each row of csv_file
    end



    # csv_text = params[:csv_content]
    # csv = CSV.parse(csv_text, :headers => true)
    # csv.each do |row|
    #   process_csv(row)
    # end # end each
    @new_data
    render action: :index
  end

  private
  def process_csv(row)
    url = row[0]
    range = row[1]
    pattern = row[2]
    street = row[3]
    company = row[4]
    suite = row[5]
    zip = row[6]

    if range.split.length == 3
      first_num = range.split('to')[0].delete('\"').to_i    # get first_num from range
      second_num = range.split('to')[1].to_i                #get second_num from range
      (first_num..second_num).step(2).to_a.each do |range_num|
        @new_data << [url, '"'+range_num.to_s+'"', '""', street, company, suite, zip].join(',')
      end

    else #else range.split.length == 1
      @new_data << [url, range, '""', street, company, suite, zip].join(',')
    end # end range.split
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_parser_helper.rb
module CsvParserHelper
end

app/views/csv_parsers/index.html.erb
<h1>CSV Parsed Data</h1>
<%= raw @new_data.join('<br/>') %>

app/views/csv_parsers/new.html.erb
<h1>CsvParser</h1>

<%= form_tag(csv_parsers_path, :method=>'post', :multipart => true) do %>
 <!-- <p>
   Input your CSV content:<br />
   <%= text_area_tag "csv_content", "", :size=>"50x20" %>
 </p> -->
 <p>
   Add an attachment:<br />
   <%= file_field_tag "csv_file" %>
 </p>
 <p>
   <%= submit_tag 'Submit' %>
 </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>